class Question:
    """ Understands: question generated by vandalizer algorithm
    """
    def __init__(self, question, answer, question_type):
        self._type = question_type
        self.question = question
        self.answer = answer
