class QuestionSet:
    """ Container for the questions that are generated for a
    single article """
    def __init__(self):
        self.questions = []

    def add(self, question):
        if type(question) is Question:
            self.questions.append(question)


class Question:
    """ Understands: question generated by vandalizer algorithm
    """
    def __init__(self, source_sentence, question, answer, question_type):
        self.source_sentence = source_sentence
        self.question = question
        self.answer = answer
        self._type = question_type
